import { ApolloClient, InMemoryCache, gql } from "@apollo/client";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ Users }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome</h1>

        <p className={styles.description}></p>

        <div className={styles.grid}>
          {Users.map((user) => {
            return (
              <a key={user.id} className={styles.card}>
                <h2>{user.username} &rarr;</h2>
                <p>{user.email}</p>
                <p>{user.password}</p>
              </a>
            );
          })}
        </div>
      </main>
    </div>
  );
}
export async function getStaticProps() {
  const client = new ApolloClient({
    uri: "http://localhost:4000/graphql",
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query Users {
        users {
          id
          username
          email
          password
        }
      }
    `,
  });

  return {
    props: {
      Users: data.users,
    },
  };
}
